// ============================================================
// SECOND SCENARIOS FOR EACH CONGRESS (for replayability)
// ============================================================
const scenarios2 = {
  7: {
    text: "A bitter argument erupts over the party's name. Lenin proposes renaming the Russian Social-Democratic Labour Party to the 'Communist Party'\u2014a symbolic break with the reformist Second International. Some old Bolsheviks resist, fearing it alienates potential allies. Meanwhile, Left SRs threaten to leave the governing coalition over Brest-Litovsk. How do you navigate these identity crises?",
    choices: [
      {text: "Champion the name change enthusiastically\u2014the old name reeks of compromise with the bourgeoisie.", loyalty: 10, cunning: 0, reputation: 5, survival: 0.9, response: "You deliver a passionate speech for the new name. Lenin beams. The party becomes the Russian Communist Party (Bolsheviks). You have aligned yourself with the revolutionary vanguard."},
      {text: "Argue the name change is premature\u2014focus on winning the Civil War first.", loyalty: -5, cunning: 5, reputation: 5, survival: 0.8, response: "You urge practical priorities over symbolism. Lenin disagrees but respects your reasoning. The name change passes anyway, but you haven't made enemies."},
      {text: "Work behind the scenes to keep the Left SR coalition intact\u2014we need allies.", loyalty: 0, cunning: 10, reputation: 5, survival: 0.75, response: "You try to broker peace with the Left SRs. It's a losing cause\u2014they will revolt in July\u2014but your diplomatic instincts are noted favorably by Lenin."},
      {text: "Use the debate to attack specific rivals by questioning their revolutionary credentials.", loyalty: 5, cunning: 10, reputation: -5, survival: 0.85, response: "You turn the name debate into a loyalty test, subtly questioning whether those who hesitate are truly Bolsheviks at heart. Effective but it makes you enemies."}
    ]
  },
  8: {
    text: "The Congress debates the new Party Program and the nationalities question. Lenin advocates genuine self-determination for non-Russian peoples, while others fear this will shatter the revolution's territorial base. Separately, the Cheka's expanding powers concern some delegates\u2014is the Red Terror creating a monster? You must speak on at least one of these issues.",
    choices: [
      {text: "Support Lenin's nationalities policy\u2014self-determination will win the borderlands to our cause.", loyalty: 10, cunning: 5, reputation: 5, survival: 0.9, response: "You back Lenin's federalist approach. This is both principled and pragmatic\u2014the Red Army needs non-Russian recruits. Your position on the nationalities question is recorded favorably."},
      {text: "Argue for tighter central control\u2014the revolution cannot afford separatism during a civil war.", loyalty: 0, cunning: 5, reputation: 5, survival: 0.85, response: "You make the case for centralism. Stalin shares this view, though he keeps quiet for now. You've staked out a position that will become more relevant in the future."},
      {text: "Raise concerns about the Cheka's unchecked power\u2014even revolutionaries need accountability.", loyalty: -5, cunning: -5, reputation: 15, survival: 0.7, response: "You question whether Dzerzhinsky's Cheka has become a state within a state. It's a brave speech. The security apparatus notes your name\u2014not favorably."},
      {text: "Propose expanding the Cheka's mandate\u2014counter-revolution lurks everywhere and must be crushed.", loyalty: 5, cunning: 5, reputation: -10, survival: 0.85, response: "You call for even harsher measures against class enemies. Dzerzhinsky approves. You've made a powerful ally in the security services, at the cost of your reputation among moderates."}
    ]
  },
  9: {
    text: "The disastrous invasion of Poland is being planned. Tukhachevsky's armies will march on Warsaw to spread revolution westward. Trotsky has private doubts about the campaign's feasibility, but the mood is intoxicating\u2014world revolution seems within reach. Lenin is swept up in revolutionary optimism. Do you voice caution or ride the wave?",
    choices: [
      {text: "Enthusiastically support the Polish campaign\u2014carry the revolution to Berlin on the points of our bayonets!", loyalty: 10, cunning: -5, reputation: 5, survival: 0.85, response: "You give a rousing speech about liberating the European proletariat. The campaign will fail catastrophically at Warsaw, but for now, your enthusiasm matches the leadership's mood."},
      {text: "Privately express doubts to Trotsky\u2014the supply lines are overstretched.", loyalty: 0, cunning: 10, reputation: 0, survival: 0.85, response: "You share military concerns with Trotsky in private. When the campaign fails, you can quietly point to your foresight. But Trotsky is not the safest ally."},
      {text: "Volunteer to organize supply logistics for the Polish front\u2014make yourself indispensable.", loyalty: 5, cunning: 10, reputation: 5, survival: 0.9, response: "You take on the thankless but vital work of logistics. Whether the campaign succeeds or fails, competent organizers are always valued. A shrewd move."},
      {text: "Argue openly that the campaign is reckless\u2014we should consolidate our gains.", loyalty: -10, cunning: -5, reputation: 10, survival: 0.65, response: "You publicly question the Polish adventure. Lenin is irritated by your defeatism. When Warsaw falls, you'll be vindicated\u2014but being right about a leader's mistake is never rewarded in Soviet politics."}
    ]
  },
  10: {
    text: "Beyond the headline debates, a quieter but crucial struggle is underway: the party apparatus is expanding rapidly, and with it comes the question of who controls appointments. A new Orgburo handles organizational matters, and Stalin sits on it. Meanwhile, the terrible famine ravaging the Volga region demands a response. The American Relief Administration offers humanitarian aid. Do you accept help from capitalists?",
    choices: [
      {text: "Accept the American aid\u2014let the capitalists feed our people while we build socialism.", loyalty: 5, cunning: 10, reputation: 5, survival: 0.9, response: "You pragmatically support accepting foreign humanitarian aid. Lenin agrees\u2014the NEP spirit extends to international relations. The aid will save millions of lives while the regime consolidates."},
      {text: "Reject foreign aid\u2014it's a Trojan horse for capitalist influence and espionage.", loyalty: 5, cunning: -5, reputation: 5, survival: 0.8, response: "You oppose the aid on security grounds. You're overruled, but hardliners respect your vigilance. Some of the ARA staff will indeed be accused of espionage later."},
      {text: "Focus your energy on the Orgburo\u2014volunteer to help Stalin with party appointments.", loyalty: 5, cunning: 15, reputation: -5, survival: 0.95, response: "While others debate famine relief, you cultivate the party's organizational machinery alongside Stalin. This is where real power is being assembled, brick by boring brick."},
      {text: "Demand accountability for the famine\u2014War Communism's grain requisitions caused this catastrophe.", loyalty: -10, cunning: -10, reputation: 15, survival: 0.6, response: "You point the finger at party policy for causing the famine. This is true but unforgivable. The leadership cannot admit that its own policies killed millions. You've made yourself a target."}
    ]
  },
  11: {
    text: "The Georgian Affair is explosive. Stalin and Ordzhonikidze have brutalized Georgian Communists who resisted incorporation into a Transcaucasian Federation. Lenin, from his sickbed, is furious\u2014he calls Stalin's behavior 'Great Russian chauvinism' and dictates angry notes. Krupskaya privately seeks allies against Stalin. Do you get involved in this dangerous dispute?",
    choices: [
      {text: "Support Lenin's position on Georgia\u2014Stalin has been a bully and must be checked.", loyalty: -5, cunning: -10, reputation: 10, survival: 0.65, response: "You back Lenin on the Georgian question. But Lenin is dying, and Stalin is very much alive. When Lenin is gone, those who opposed Stalin on Georgia will have no protector."},
      {text: "Side with Stalin\u2014centralization is necessary, the Georgians are being sentimental.", loyalty: 10, cunning: 10, reputation: -5, survival: 0.9, response: "You defend the need for a unified Transcaucasian Federation. Stalin is grateful for the support. The Georgian Communists are crushed. Centralism triumphs."},
      {text: "Propose a diplomatic compromise\u2014give Georgia nominal autonomy within the federation structure.", loyalty: 0, cunning: 10, reputation: 5, survival: 0.85, response: "You try to split the difference. Neither Stalin nor the Georgians are fully satisfied, but you've avoided making a clear enemy. A survivor's instinct."},
      {text: "Avoid the Georgian question entirely\u2014focus your Congress speech on trade and industry.", loyalty: 0, cunning: 15, reputation: 0, survival: 0.9, response: "You give a thoroughly dull speech about industrial statistics, skating past the Georgian controversy as if it doesn't exist. No one remembers your contribution. Perfect."}
    ]
  },
  12: {
    text: "The 'Scissors Crisis' is devastating the economy\u2014industrial prices are soaring while agricultural prices collapse, threatening the entire NEP. Trotsky and his supporters argue this proves the need for central economic planning and rapid industrialization. The Troika dismisses this as opposition alarmism. Meanwhile, everyone is jockeying for influence over Lenin's political legacy. How do you position yourself economically?",
    choices: [
      {text: "Back Trotsky's economic analysis\u2014the Scissors Crisis demands centralized planning.", loyalty: -10, cunning: 0, reputation: 10, survival: 0.6, response: "You support Trotsky's economic diagnosis. It's intellectually sound\u2014Stalin himself will adopt similar policies in five years. But supporting Trotsky now marks you as opposition."},
      {text: "Support the Troika's line\u2014the NEP will self-correct, market forces need time.", loyalty: 10, cunning: 5, reputation: 0, survival: 0.85, response: "You back the official optimism about NEP. The Troika rewards loyalty. The Scissors Crisis does eventually ease, vindicating your patience\u2014or at least appearing to."},
      {text: "Propose technical reforms to close the scissors\u2014price controls on key industrial goods.", loyalty: 5, cunning: 10, reputation: 10, survival: 0.9, response: "You offer concrete policy proposals rather than factional position-taking. Both sides find something to like in your pragmatic approach. Technocratic competence is your shield."},
      {text: "Argue that the real priority is building Lenin's cult\u2014the succession requires ideological clarity.", loyalty: 5, cunning: 10, reputation: -5, survival: 0.85, response: "You pivot from economics to ideology, proposing elaborate measures to preserve Lenin's legacy. This pleases Stalin, who is already constructing the cult of Lenin as a tool of legitimation."}
    ]
  },
  13: {
    text: "The 'Literary Discussion' rages through the party. Trotsky has published 'Lessons of October,' attacking Zinoviev and Kamenev for opposing the Bolshevik seizure of power in 1917. The Troika retaliates by inventing 'Trotskyism' as a deviation from Leninism. Every party cell must pass resolutions condemning Trotskyism. Your local organization demands you speak. What do you say?",
    choices: [
      {text: "Deliver a scathing denunciation of Trotskyism\u2014it is a petty-bourgeois deviation from Leninism.", loyalty: 10, cunning: 5, reputation: -5, survival: 0.9, response: "You parrot the anti-Trotsky line with gusto. The Troika is pleased. Your denunciation is published in Pravda. But you've burned any bridge to Trotsky's camp."},
      {text: "Defend Trotsky's record in the Revolution and Civil War\u2014his contributions are undeniable.", loyalty: -15, cunning: -10, reputation: 10, survival: 0.45, response: "You dare to defend Trotsky. The room goes silent, then hostile. Your speech is reported upward. You have shown extraordinary courage and extraordinary political foolishness."},
      {text: "Condemn factionalism in general terms without naming Trotsky specifically.", loyalty: 0, cunning: 10, reputation: 0, survival: 0.85, response: "You give a speech about party unity that could apply to anyone. The Troika wants more, but you haven't committed the sin of defending Trotsky. A careful tightrope walk."},
      {text: "Steer the discussion to economic achievements in your region\u2014refuse to engage in the literary debate.", loyalty: 0, cunning: 10, reputation: 0, survival: 0.85, response: "You bore your comrades with production statistics rather than taking sides. Some accuse you of cowardice. You call it focus on practical work. Both are true."}
    ]
  },
  14: {
    text: "Krupskaya, Lenin's widow, has thrown her moral authority behind the New Opposition. She reads a statement at the Congress criticizing the suppression of debate. Her intervention shocks the hall\u2014can you attack Lenin's own wife? Stalin reportedly said: 'The party can always find Lenin a new widow.' Meanwhile, Bukharin has emerged as Stalin's chief ideological ally, defending NEP. Where do you stand?",
    choices: [
      {text: "Publicly respect Krupskaya but vote against her position\u2014she is mistaken, not malicious.", loyalty: 5, cunning: 15, reputation: 5, survival: 0.9, response: "You thread the needle perfectly\u2014honoring Lenin's memory through his widow while supporting the majority. This requires political artistry, and you pull it off."},
      {text: "Attack Krupskaya\u2014being Lenin's widow doesn't make her infallible.", loyalty: 10, cunning: 0, reputation: -10, survival: 0.85, response: "You take the aggressive line. Stalin approves of your toughness, but many delegates are uncomfortable seeing Lenin's widow attacked. You've shown you'll go far for the boss."},
      {text: "Support Krupskaya and the New Opposition\u2014they represent Lenin's true legacy.", loyalty: -15, cunning: -10, reputation: 10, survival: 0.4, response: "You rally to Krupskaya's side. It's a noble stand in defense of the party's democratic traditions. It is also political suicide. The New Opposition is outvoted overwhelmingly."},
      {text: "Ally with Bukharin on economic policy\u2014defend the NEP and the peasant alliance.", loyalty: 10, cunning: 10, reputation: 5, survival: 0.9, response: "You become a vocal supporter of Bukharin's pro-peasant economics. The Stalin-Bukharin alliance is the winning coalition\u2014for now. In three years, Bukharin himself will be the target."}
    ]
  },
  15: {
    text: "The party apparatus has discovered an underground opposition printing press. Trotsky's supporters have been distributing leaflets criticizing Stalin's policies\u2014a clear violation of the faction ban. The GPU (secret police) wants to treat this as a criminal conspiracy. Meanwhile, the First Five-Year Plan is being drafted. The industrialization debate is reaching its climax: gradual growth or breakneck transformation?",
    choices: [
      {text: "Demand criminal prosecution of the underground press operators\u2014factionalism is now treason.", loyalty: 10, cunning: 5, reputation: -10, survival: 0.9, response: "You call for the harshest measures. The secret police is grateful for political cover. You have helped establish the precedent that political opposition equals criminal conspiracy."},
      {text: "Argue for lenient treatment\u2014expulsion from the party is sufficient, no need for prison.", loyalty: -5, cunning: 0, reputation: 10, survival: 0.7, response: "You advocate mercy. This is seen as softness by the hardliners and fails to impress the opposition, who are beyond saving. A losing position from every angle."},
      {text: "Focus your energy on the Five-Year Plan\u2014push for ambitious but achievable industrial targets.", loyalty: 5, cunning: 10, reputation: 5, survival: 0.9, response: "You throw yourself into planning work, advocating bold but realistic targets. As the party shifts leftward toward rapid industrialization, your expertise becomes valuable."},
      {text: "Push for the most extreme industrialization targets possible\u2014prove you're more radical than the Left.", loyalty: 10, cunning: 10, reputation: 0, survival: 0.85, response: "You out-left the Left, demanding even faster industrialization than Trotsky ever proposed. This mirrors Stalin's own pivot. Anticipating the leader's direction is the supreme survival skill."}
    ]
  },
  16: {
    text: "Whispers spread about the true scale of the famine in Ukraine and Kazakhstan. Millions are dying. Foreign journalists are being kept away. A colleague privately confides that conditions in his region are catastrophic and asks if you'll jointly raise the issue with the leadership. Meanwhile, the show trial of the 'Industrial Party' is being prepared\u2014engineers accused of sabotage and wrecking. The scapegoating has begun.",
    choices: [
      {text: "Report your colleague's complaint to the party authorities\u2014this kind of defeatism aids the enemy.", loyalty: 15, cunning: 5, reputation: -15, survival: 0.85, response: "You denounce your colleague. He disappears from public life. You have demonstrated the cold ruthlessness that Stalin's system rewards. But you will sleep uneasily."},
      {text: "Privately sympathize with your colleague but refuse to act\u2014stay silent and survive.", loyalty: 0, cunning: 10, reputation: 0, survival: 0.8, response: "You listen, nod, and do nothing. You neither report him nor help him. This moral cowardice is the most common survival strategy in the Soviet system."},
      {text: "Support the Industrial Party trial\u2014wreckers and saboteurs must be exposed and punished.", loyalty: 10, cunning: 5, reputation: -5, survival: 0.85, response: "You vocally support the show trial, providing the political legitimacy that the OGPU needs. The engineers are convicted. You've helped build the machinery of terror."},
      {text: "Quietly arrange for food supplies to be diverted to the worst-hit areas through your contacts.", loyalty: 0, cunning: 5, reputation: 10, survival: 0.7, response: "You use your position to alleviate the famine in small ways, without public fanfare. It's humanitarian but risky\u2014any unauthorized deviation from central plans can be called sabotage."}
    ]
  },
  17: {
    text: "After the Congress, Kirov is assassinated in December 1934\u2014shot in the Smolny Institute in Leningrad. Stalin arrives personally to investigate. The murder will be used as the pretext for the Great Terror. In the immediate aftermath, you are asked to sign a resolution demanding the death penalty for 'terrorists.' Refusal to sign is unthinkable. But how far do you go?",
    choices: [
      {text: "Sign immediately and demand the harshest measures\u2014add a personal statement calling for the extermination of enemies.", loyalty: 15, cunning: 5, reputation: -15, survival: 0.75, response: "You lead the charge for repression. Your zeal is noted. But the most enthusiastic executioners sometimes become the next victims\u2014Stalin trusts no one, especially those who seem too eager."},
      {text: "Sign the resolution quietly\u2014do what is required, nothing more.", loyalty: 5, cunning: 15, reputation: 0, survival: 0.85, response: "You sign and return to your work. You do not volunteer additional denunciations. You do not draw attention to yourself. In the coming storm, invisibility is the highest art."},
      {text: "Sign but privately investigate the circumstances\u2014something about Kirov's murder doesn't add up.", loyalty: -5, cunning: 5, reputation: 5, survival: 0.5, response: "You notice inconsistencies in the official story. Kirov's bodyguard was mysteriously absent. But investigating the murder means investigating Stalin's possible role. This knowledge is deadly."},
      {text: "Use the crisis to settle scores\u2014provide the NKVD with names of your rivals as 'suspected contacts' of the assassin.", loyalty: 5, cunning: 5, reputation: -15, survival: 0.7, response: "You feed names to the NKVD. Some of your rivals are arrested. But the machine of denunciation is indiscriminate\u2014those you've denounced may name you in their forced confessions."}
    ]
  },
  18: {
    text: "The Molotov-Ribbentrop Pact has just been signed. Yesterday's mortal enemy\u2014Nazi Germany\u2014is now an ally. Communist parties worldwide are thrown into confusion. Anti-fascist rhetoric must be abandoned overnight. At the Congress, you must explain this 180-degree turn to bewildered delegates. Meanwhile, the Soviet Union is about to invade Poland from the east, dividing it with Hitler.",
    choices: [
      {text: "Praise the Pact as a masterpiece of Soviet diplomacy\u2014Stalin has outwitted the Western imperialists.", loyalty: 10, cunning: 10, reputation: 0, survival: 0.9, response: "You deliver a speech praising the 'genius of Comrade Stalin's foreign policy.' The pact buys time for military preparation, you argue. Delegates nod along. Cognitive dissonance is a survival skill."},
      {text: "Focus on the military implications\u2014use the breathing space to rearm and prepare.", loyalty: 5, cunning: 15, reputation: 5, survival: 0.9, response: "You steer discussion to practical military readiness rather than ideological gymnastics. This is the most useful response and draws no political fire."},
      {text: "Express private unease to trusted colleagues\u2014allying with fascists betrays everything we stand for.", loyalty: -10, cunning: -10, reputation: 10, survival: 0.5, response: "You share your moral doubts quietly. But after the Terror, there are no trusted colleagues. Your words will be reported. In Stalin's USSR, there is no private sphere."},
      {text: "Volunteer to manage the occupation of eastern Poland\u2014show eagerness for the new territorial gains.", loyalty: 10, cunning: 5, reputation: -5, survival: 0.8, response: "You volunteer for the grim work of occupying eastern Poland and the Baltics. This involves mass deportations and political repression. But it demonstrates your willingness to serve."}
    ]
  },
  19: {
    text: "Stalin delivers a rambling, menacing speech at the Congress. He attacks Molotov and Mikoian by name, accusing them of cowardice and ideological weakness. Everyone understands the signal: no one is safe, no matter how long they've served. Molotov's wife Polina has already been arrested. The expansion of the Presidium from 11 to 25 members clearly aims to dilute the old guard. A new purge seems imminent. How do you react?",
    choices: [
      {text: "Applaud Stalin's speech enthusiastically and publicly distance yourself from Molotov.", loyalty: 10, cunning: 10, reputation: -10, survival: 0.85, response: "You abandon your old comrade Molotov to save yourself. He notices. If Stalin dies and Molotov returns to power, you will pay. But if Stalin lives, this was the right move."},
      {text: "Stay absolutely silent\u2014do not react to the attacks on Molotov and Mikoian one way or another.", loyalty: 0, cunning: 15, reputation: 0, survival: 0.85, response: "You become a statue during Stalin's speech. Neither condemning nor defending. The paranoid old dictator might interpret silence as defiance\u2014or he might not notice you at all. A gamble."},
      {text: "Quietly reach out to other old guard members\u2014form a discreet mutual protection network.", loyalty: -5, cunning: 5, reputation: 5, survival: 0.55, response: "You try to organize quiet resistance among the threatened veterans. But the NKVD penetrates everything. Conspiring against Stalin, even defensively, is the most dangerous act possible."},
      {text: "Throw yourself into the Doctors' Plot narrative\u2014provide 'evidence' of the conspiracy.", loyalty: 10, cunning: 0, reputation: -15, survival: 0.7, response: "You contribute to the anti-Semitic hysteria of the Doctors' Plot. It may buy short-term favor, but when Stalin dies in four months, those most associated with this plot will be politically toxic."}
    ]
  },
  20: {
    text: "The Secret Speech has sent shockwaves through the Communist world. In Poland, workers riot in Poznan. In Hungary, revolution erupts\u2014Nagy's government tries to leave the Warsaw Pact. Khrushchev faces a choice: let Hungary go or send in the tanks. You are consulted. Meanwhile, Chinese leader Mao privately criticizes the speech for destabilizing the entire Communist movement.",
    choices: [
      {text: "Advocate military intervention in Hungary\u2014we cannot allow a socialist state to fall.", loyalty: 10, cunning: 5, reputation: -5, survival: 0.9, response: "You support crushing the Hungarian Revolution. Soviet tanks roll into Budapest. Thousands die. But the Warsaw Pact holds together. Your hardline position aligns with the eventual decision."},
      {text: "Argue for a political solution in Hungary\u2014military intervention will discredit socialism worldwide.", loyalty: -5, cunning: 5, reputation: 10, survival: 0.75, response: "You advocate negotiation over force. Khrushchev initially hesitates but ultimately chooses tanks. Your counsel was rejected, but your willingness to dissent is noted by reformist colleagues."},
      {text: "Focus on managing the domestic fallout of the Secret Speech\u2014rehabilitations, released prisoners, reckoning.", loyalty: 5, cunning: 10, reputation: 5, survival: 0.9, response: "You concentrate on the practical work of de-Stalinization at home: reviewing cases, rehabilitating victims, reforming the security services. This useful work keeps you out of the Hungary debate."},
      {text: "Side with Mao's criticism\u2014the Secret Speech was reckless and has destabilized the entire movement.", loyalty: -5, cunning: 5, reputation: 0, survival: 0.7, response: "You echo Chinese concerns about the speech's destabilizing effects. This doesn't endear you to Khrushchev but positions you as a voice of caution. The Sino-Soviet split will make this position untenable."}
    ]
  },
  21: {
    text: "Khrushchev's Virgin Lands campaign is showing cracks. Initial bumper harvests have given way to soil erosion and declining yields. He is now pushing for a massive expansion of corn cultivation\u2014'the queen of the fields'\u2014after visiting Iowa. Many agricultural scientists privately consider this inappropriate for Soviet climatic conditions. Your region is being pressured to plant corn. What do you do?",
    choices: [
      {text: "Plant the corn enthusiastically and report spectacular (fabricated) yields.", loyalty: 10, cunning: 5, reputation: -5, survival: 0.85, response: "You cover your fields with corn and your reports with optimistic statistics. When the crop fails, you blame weather and saboteurs. The Soviet system runs on creative accounting."},
      {text: "Present scientific data showing corn is unsuitable for your region's climate.", loyalty: -10, cunning: -5, reputation: 10, survival: 0.6, response: "You dare to challenge the leader's pet project with facts. Khrushchev is enraged\u2014he dismisses scientists who disagree with him. Being right is once again the most dangerous position."},
      {text: "Plant corn in the visible areas near roads; keep proven crops in the back fields.", loyalty: 5, cunning: 15, reputation: 0, survival: 0.9, response: "A classic Soviet compromise\u2014Potemkin cornfields for the inspectors, real crops where they matter. This quiet subversion of absurd orders is how the Soviet economy actually functioned."},
      {text: "Redirect the conversation to your region's industrial achievements\u2014change the subject from agriculture.", loyalty: 0, cunning: 10, reputation: 0, survival: 0.85, response: "You pivot every agricultural discussion to industrial output, where your numbers are better. Khrushchev wants to talk about corn, but he also cares about steel and chemicals."}
    ]
  },
  22: {
    text: "Khrushchev announces the new Party Program, promising full communism by 1980. Private apartments for every family, free public transport, the abolition of money\u2014utopian promises that no one in the leadership truly believes. But you must endorse the Program at the Congress. Meanwhile, Khrushchev is splitting the party into industrial and agricultural branches\u2014a reorganization that threatens every apparatchik's power base.",
    choices: [
      {text: "Embrace the Party Program's vision of communism by 1980\u2014inspire the masses with the dream.", loyalty: 10, cunning: 0, reputation: 0, survival: 0.8, response: "You deliver an inspiring speech about the communist future. Nobody believes it, including you. But enthusiasm for the Program is required. When 1980 arrives under Brezhnev, no one will mention it."},
      {text: "Support the party reorganization\u2014it will bring the apparatus closer to production.", loyalty: 5, cunning: -5, reputation: 0, survival: 0.75, response: "You back Khrushchev's structural reorganization. This puts you in his good graces but alienates the party apparatus, which hates having its power structures disrupted. Risky."},
      {text: "Quietly build alliances with those opposed to the reorganization\u2014the apparatus will fight back.", loyalty: -5, cunning: 15, reputation: 0, survival: 0.9, response: "You recognize that the party apparatus will eventually rebel against Khrushchev's meddling. You build relationships with Brezhnev, Suslov, and other conservatives who share this view."},
      {text: "Focus on the space program\u2014Gagarin's triumph is the one unambiguously good story to tell.", loyalty: 5, cunning: 10, reputation: 5, survival: 0.85, response: "You become the party's champion of space achievements. Gagarin's flight is genuine glory. Attaching yourself to unambiguous success is always wise."}
    ]
  },
  23: {
    text: "The Sinyavsky-Daniel trial has put culture and censorship at the center of political debate. Two writers have been imprisoned for publishing satirical works abroad. Western intellectuals protest; Soviet liberals are dismayed. Brezhnev's leadership must decide: how much intellectual freedom is compatible with party control? Separately, the question of how far to rehabilitate Stalin is fiercely debated behind closed doors.",
    choices: [
      {text: "Support the crackdown on dissident writers\u2014publishing abroad is treasonous.", loyalty: 10, cunning: 5, reputation: -5, survival: 0.9, response: "You back the hard line on culture. The KGB appreciates your support. The trial becomes a turning point\u2014the beginning of the Brezhnev-era cultural freeze."},
      {text: "Argue for a more nuanced cultural policy\u2014repression only drives dissent underground.", loyalty: -5, cunning: 5, reputation: 10, survival: 0.75, response: "You quietly advocate for a lighter touch. Some in the leadership agree\u2014but the hardliners prevail. Your moderate position marks you as unreliable to the security establishment."},
      {text: "Push for partial rehabilitation of Stalin\u2014restore respect for the war victory and industrialization.", loyalty: 5, cunning: 10, reputation: 0, survival: 0.85, response: "You advocate a calibrated re-Stalinization: honor the achievements while maintaining criticism of 'excesses.' This is exactly Brezhnev's preferred position\u2014the cautious middle ground."},
      {text: "Propose expanding Kosygin's economic reforms as the real priority\u2014culture is a distraction.", loyalty: 0, cunning: 10, reputation: 5, survival: 0.8, response: "You try to redirect attention to economic modernization. Kosygin appreciates the support, but Brezhnev is wary of reforms that weaken central party control. The reforms will be slowly strangled."}
    ]
  },
  24: {
    text: "The Prague Spring's aftermath poisons international relations. The 'Brezhnev Doctrine' declaring the right to intervene in any socialist state has alarmed even some allies. At home, the dissident movement grows\u2014Solzhenitsyn's works circulate in samizdat, Sakharov publishes his manifesto. A KGB report crosses your desk warning that dissidents have foreign contacts. How do you handle this sensitive intelligence?",
    choices: [
      {text: "Recommend aggressive action against the dissidents\u2014psychiatric hospitals, exile, imprisonment.", loyalty: 10, cunning: 5, reputation: -10, survival: 0.9, response: "You support the KGB's harshest proposals. Dissidents are committed to psychiatric hospitals, their works confiscated. The security services reward your loyalty with information and support."},
      {text: "Suggest a measured response\u2014monitor but don't create martyrs that Western media can exploit.", loyalty: 5, cunning: 15, reputation: 5, survival: 0.9, response: "You advocate strategic restraint. Martyring dissidents plays into Western propaganda. Better to isolate them socially and professionally. Andropov, the KGB chief, appreciates this sophisticated thinking."},
      {text: "Ignore the report and focus on d\u00e9tente\u2014better relations with the West matter more than a few dissidents.", loyalty: 0, cunning: 5, reputation: 5, survival: 0.85, response: "You downplay the dissident threat in favor of the bigger picture. D\u00e9tente with Nixon is producing real benefits. But ignoring KGB reports can be seen as dereliction."},
      {text: "Quietly leak the KGB report to a trusted Western journalist to embarrass the security services.", loyalty: -20, cunning: 0, reputation: 15, survival: 0.3, response: "You commit what amounts to treason against the Soviet state. If discovered\u2014and the KGB is very good at discovering things\u2014you face prison or worse. An extraordinarily dangerous moral stand."}
    ]
  },
  25: {
    text: "Brezhnev wants the Congress to ratify the new 'Brezhnev Constitution' of 1977, which will enshrine the party's leading role in Article 6. He also wants a new military decoration named after himself. The sycophancy reaches absurd heights\u2014delegates compete to praise the leader most extravagantly. Meanwhile, economic reports crossing your desk show alarming trends: declining growth, rising dependence on oil exports, technological lag behind the West.",
    choices: [
      {text: "Nominate Brezhnev for the Lenin Prize in Literature for his ghostwritten memoirs\u2014maximum flattery.", loyalty: 15, cunning: 5, reputation: -10, survival: 0.95, response: "You propose the most absurd honor imaginable\u2014and it's approved. Brezhnev is delighted. The entire hall applauds. You have mastered the art of the Brezhnev-era court: sincerity is irrelevant, performance is everything."},
      {text: "Present a confidential economic analysis to the leadership showing the severity of stagnation.", loyalty: -5, cunning: 5, reputation: 10, survival: 0.8, response: "You prepare an honest assessment of economic decline. Andropov reads it with interest. Most of the Politburo ignores it. But you've planted a seed and impressed the man who will succeed Brezhnev."},
      {text: "Propose modest economic reforms\u2014efficiency improvements that don't threaten the system.", loyalty: 0, cunning: 10, reputation: 5, survival: 0.85, response: "You suggest technocratic tweaks: better quality control, management incentives, limited autonomy for enterprises. They're adopted on paper and ignored in practice. The system resists reform."},
      {text: "Focus on securing more resources for your region or ministry\u2014play the patronage game.", loyalty: 5, cunning: 15, reputation: 0, survival: 0.95, response: "You use the Congress to negotiate budget allocations, construction projects, and appointments for your fiefdom. This is how the Brezhnev system actually works\u2014a vast patronage network. You thrive within it."}
    ]
  },
  26: {
    text: "Poland's Solidarity movement presents an existential crisis. Ten million Poles have joined an independent trade union\u2014the first in any Communist country. The Polish party is losing control. Hawks demand military intervention as in 1968. Doves warn that Poland is not Czechoslovakia\u2014an invasion would be far bloodier and could destroy d\u00e9tente entirely. The debate in the Politburo is intense.",
    choices: [
      {text: "Advocate Soviet military intervention\u2014we cannot allow Poland to leave the socialist camp.", loyalty: 10, cunning: 0, reputation: -5, survival: 0.8, response: "You push for tanks in Warsaw. The leadership ultimately opts for Polish martial law instead\u2014General Jaruzelski does the dirty work. Your hawkishness was noted but the Soviet military was relieved not to invade."},
      {text: "Support Polish martial law as a compromise\u2014let the Poles handle it themselves.", loyalty: 5, cunning: 15, reputation: 0, survival: 0.9, response: "You advocate the solution that is ultimately adopted: pressure Jaruzelski to impose martial law. This avoids the costs of invasion while crushing Solidarity. A pragmatic and prescient position."},
      {text: "Warn that Solidarity reflects genuine worker grievances that exist in the USSR too.", loyalty: -10, cunning: -5, reputation: 10, survival: 0.6, response: "You draw uncomfortable parallels between Polish and Soviet workers' frustrations. This is brave and accurate, but the Politburo does not want to hear that the disease might be contagious."},
      {text: "Use the Polish crisis to argue for accelerating Andropov's anti-corruption campaign at home.", loyalty: 5, cunning: 10, reputation: 5, survival: 0.9, response: "You argue that preventing a Soviet Solidarity requires addressing domestic corruption and cynicism. This aligns with Andropov's agenda and positions you well for the coming succession."}
    ]
  },
  27: {
    text: "Chernobyl has just exploded. The initial cover-up\u2014days of silence while radiation spread across Europe\u2014has become a symbol of everything wrong with the old system. Gorbachev is furious at the lies and delays. He uses Chernobyl to accelerate glasnost: if the system can't tell the truth about a nuclear disaster, what can it tell the truth about? Old guard members resist this logic. Where do you stand?",
    choices: [
      {text: "Use Chernobyl to champion radical glasnost\u2014the system of lies must end completely.", loyalty: 10, cunning: 5, reputation: 15, survival: 0.8, response: "You become a vocal advocate for transparency. Gorbachev appreciates your support. But glasnost is unleashing truths that will destroy the system itself\u2014the Molotov-Ribbentrop secret protocols, the Katyn massacre, the full scale of Stalin's crimes."},
      {text: "Argue that Chernobyl was a technical failure, not a systemic one\u2014don't use it to attack the party.", loyalty: -5, cunning: 5, reputation: -5, survival: 0.7, response: "You try to limit the political damage from Chernobyl. The conservative faction appreciates your restraint, but Gorbachev sees this as obstruction. You're swimming against the current."},
      {text: "Focus on the practical response\u2014evacuation, decontamination, reactor safety\u2014rather than the political implications.", loyalty: 5, cunning: 15, reputation: 5, survival: 0.9, response: "You throw yourself into the practical work of disaster response. Being competent and useful during a crisis is always the best survival strategy, regardless of which faction prevails."},
      {text: "Propose that nuclear energy decisions should involve public consultation\u2014a radical democratic suggestion.", loyalty: 0, cunning: 5, reputation: 10, survival: 0.75, response: "You propose democratizing technical decisions. This is ahead of its time and aligns with Gorbachev's vision, but it terrifies the military-industrial complex, which has always operated in secrecy."}
    ]
  },
  28: {
    text: "The Congress degenerates into open warfare between factions. A conservative colonel gives an impassioned speech demanding order be restored. Reformers demand the party transform into a social-democratic party. National delegations from the Baltic republics announce they will form independent parties. Gorbachev tries to hold the center. The air is electric with the sense that an era is ending. What is your final political act?",
    choices: [
      {text: "Give an emotional speech defending the party's 73-year history\u2014it cannot end like this.", loyalty: 10, cunning: 0, reputation: 5, survival: 0.65, response: "You make an impassioned defense of the Communist Party. Some delegates weep. But sentiment cannot save a dying institution. Within eighteen months, the party will be banned and the USSR dissolved."},
      {text: "Propose transforming the CPSU into a modern social-democratic party\u2014evolution, not extinction.", loyalty: 0, cunning: 10, reputation: 10, survival: 0.7, response: "You advocate the transformation path. It's the most intellectually honest position\u2014but neither the hardliners nor the radicals accept it. The center cannot hold when the extremes pull this hard."},
      {text: "Announce your candidacy for president of your republic\u2014the future is in sovereign states, not the Union.", loyalty: -15, cunning: 15, reputation: 10, survival: 0.85, response: "You pivot to republican politics, recognizing that real power is flowing from Moscow to the republics. Many party officials will make this transition successfully, becoming the leaders of newly independent states."},
      {text: "Begin networking with Western business contacts\u2014the real game now is economic transformation.", loyalty: -10, cunning: 20, reputation: -10, survival: 0.95, response: "You see the future clearly: the planned economy is dead, and those who position themselves at the intersection of state assets and private capital will become fabulously wealthy. The age of the oligarchs is dawning."}
    ]
  }
};
